version: '3.1'
services:

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql